[project]
name = "fast-pmtiles"
version = "0.1.1"
description = "Vector Tile Proxy for PMTiles"
authors = [
    { name = "Brendan McAndrew", email = "19274445+bmcandr@users.noreply.github.com" },
]
urls = { Source = "https://github.com/bmcandr/fast-pmtiles" }
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
license-files = ["LICEN[CS]E*"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Framework :: FastAPI",
]

dependencies = [
    "aiohttp>=3.13.3",
    "async-pmtiles>=0.1.0",
    "cachetools>=7.0.1",
    "fastapi[standard]>=0.128.8",
    "jinja2>=3.1.6",
    "obstore>=0.8.2",
]

[dependency-groups]
dev = [
    "pre-commit>=4.5.1",
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
    "pytest-recording>=0.13.4",
    "ruff>=0.15.0",
    "ty>=0.0.16",
]

[tool.ruff]
target-version = "py313"

[tool.ruff.lint]
extend-select = ["UP"]

[tool.pytest.ini_options]
pythonpath = ["src"]
