name: Release

on:
  release:
    types:
      - published

jobs:
  release:
    name: release
    environment:
      name: release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    if: ${{ github.repository == 'bmcandr/fast-pmtiles' }}
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Build
        run: uv build

      - name: Publish to PyPI
        run: uv publish
